-- Copy data from internal stage into Snowflake table
COPY INTO SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES
FROM @%SUPERSTORE_SALES
FILE_FORMAT = (
  TYPE = 'CSV',
  FIELD_OPTIONALLY_ENCLOSED_BY = '"',
  SKIP_HEADER = 1
)
ON_ERROR = 'CONTINUE';
