-- Create database and schema
CREATE DATABASE IF NOT EXISTS SALES_PIPELINE;
CREATE SCHEMA IF NOT EXISTS SALES_PIPELINE.RAW_DATA;

-- Create the raw Superstore sales table
CREATE OR REPLACE TABLE SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES (
    ROW_ID INT,
    ORDER_ID STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SHIP_MODE STRING,
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    SEGMENT STRING,
    COUNTRY STRING,
    CITY STRING,
    STATE STRING,
    POSTAL_CODE STRING,
    REGION STRING,
    PRODUCT_ID STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    PRODUCT_NAME STRING,
    SALES FLOAT,
    QUANTITY INT,
    DISCOUNT FLOAT,
    PROFIT FLOAT
);

