-- Dimension: Customer
CREATE OR REPLACE TABLE SALES_PIPELINE.RAW_DATA.DIM_CUSTOMER AS
SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    COUNTRY,
    CITY,
    STATE,
    POSTAL_CODE,
    REGION
FROM SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES;

-- Dimension: Product
CREATE OR REPLACE TABLE SALES_PIPELINE.RAW_DATA.DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY
FROM SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES;

-- Dimension: Date
CREATE OR REPLACE TABLE SALES_PIPELINE.RAW_DATA.DIM_DATE AS
SELECT DISTINCT
    ORDER_DATE AS DATE_ACTUAL,
    TO_CHAR(ORDER_DATE, 'YYYY') AS YEAR,
    TO_CHAR(ORDER_DATE, 'MM') AS MONTH,
    TO_CHAR(ORDER_DATE, 'DY') AS WEEKDAY
FROM SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES
WHERE ORDER_DATE IS NOT NULL;

-- Fact Table
CREATE OR REPLACE TABLE SALES_PIPELINE.RAW_DATA.FACT_SALES AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT
FROM SALES_PIPELINE.RAW_DATA.SUPERSTORE_SALES;
